version: '3.9'

services:

  flask_db:

    env_file: ./docker/.env-postgresql 
    container_name: flask_db
    image: postgres:12
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      laba:

  flask_app:

    container_name: flask_app
    restart: unless-stopped
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_URL=postgresql://postgres_user:postgres_user_password@flask_db:5432/db_name
    depends_on:
      - flask_db
    networks:
      laba:
 
networks:
  laba:
    driver: bridge
